title: Ali Badri
logo: /assets/photo_2024-03-14_23-42-40.jpg
#description: text below image
# show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
